@echo off
REM 设置输入和输出路径
set input_folder=D:\Excel2JsonTool\ExcelFolder
set output_project_folder=D:\Excel2JsonTool\ProjectFolder\Json
set csfile_output_folder=D:\Excel2JsonTool\ProjectFolder\ConfigData\AutoGeneratedScript
set enum_output_folder=D:\Excel2JsonTool\ProjectFolder\ConfigData\AutoGeneratedEnum

REM 运行python脚本, 首次导出需要配置正确的本地python目录
"C:\Program Files\Python 3.13.0\python.exe" ..\ExcelExportTool\export_all.py %input_folder% %output_project_folder% %csfile_output_folder% %enum_output_folder%
pause
