using System.Collections.Generic;
using Newtonsoft.Json;


namespace Data.TableScript
{
	/// <summary> This is auto-generated, don't modify manually </summary>
	public class RefExampleInfo : IConfigRawInfo
	{
		/// <summary> 编号: 这是被引用的字段 </summary>
		[JsonProperty("id")]
		public int id { get; private set; }
		
		/// <summary> 名称 </summary>
		[JsonProperty("name")]
		public string name { get; private set; }
		
		/// <summary> 描述 </summary>
		[JsonProperty("desc")]
		public string desc { get; private set; }
	}
	
	/// <summary>
	/// Config data class for RefExample. Generated by tool.
	/// Query methods are provided by ConfigManager; keep this class minimal.
	/// </summary>
	public class RefExampleConfig : ConfigDataBase<RefExampleInfo>
	{
	
	}
}